### ISSUE TITLE
Security hole in initramdisk script

### ISSUE THREAD

**Issue by FlorentRevest** [shr-distribution/meta-smartphone#1]
Hi,
I'm using meta-smartphone for one of my projects and when reading the initramdisk script I noticed [this line](https://github.com/shr-distribution/meta-smartphone/blob/shr/meta-android/recipes-core/initrdscripts/initramfs-boot-android/init.sh#L70). It basicaly means that if a user adds an innocent script to the sdcard (he probably has rw rights on it), it will be executed with full root rights on the next boot.
I think we can agree on the fact that it's not desirable and we should find a workaround.

**Comment by Tofee** [comment]
We're now using Halium scripts to boot our Android device; this line isn't present in Halium, so it shouldn't be a problem anymore.
